FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# 👇 build du dossier contenant main.go
RUN go build -o app ./cmd/server

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/app .

EXPOSE 5000

CMD ["./app"]
