// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates a user via email or username and returns a JWT cookie on success.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login a user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "logged in successfully",
                        "schema": {
                            "$ref": "#/definitions/response.MessageResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Clears the JWT cookie and invalidates the user's session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout the current user",
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "schema": {
                            "$ref": "#/definitions/response.MessageResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves information about the currently logged-in user based on the JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current user info",
                "responses": {
                    "200": {
                        "description": "Current user information",
                        "schema": {
                            "$ref": "#/definitions/model.UserMeJWT"
                        }
                    }
                }
            }
        },
        "/teams": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of all registered teams \u0026 their members. 🔒 Requires role: **admin**",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Get all teams",
                "responses": {
                    "200": {
                        "description": "List of teams retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.TeamReadAll"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new team with the provided details. You can add members or not. 🔒 Requires role: **admin**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Create a new team",
                "parameters": [
                    {
                        "description": "Team to create",
                        "name": "team",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TeamCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Team created successfully"
                    }
                }
            }
        },
        "/teams/add-users": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds users to an existing team by their UUIDs. 🔒 Requires role: **admin**",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Add users to a team",
                "parameters": [
                    {
                        "description": "Team UUID and User UUIDs to add",
                        "name": "team_users",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TeamAddUsers"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Users added to team successfully"
                    }
                }
            }
        },
        "/teams/edit/{uuid}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates an existing team's details by its UUID. 🔒 Requires role: **admin**",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Update team by UUID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated team details",
                        "name": "team",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TeamUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Team updated successfully"
                    }
                }
            }
        },
        "/teams/users/{team_uuid}/{user_uuid}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes a user from a team by the provided team UUID and user UUID. 🔒 Requires role: **admin**",
                "tags": [
                    "Teams"
                ],
                "summary": "Remove user from team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team UUID",
                        "name": "team_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "user_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "User removed from team successfully"
                    }
                }
            }
        },
        "/teams/{team_uuid}/users/{user_uuid}/edit-manager-status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a team member's manager status by team UUID and user UUID. 🔒 Requires role: **admin**",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Update team member manager status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team UUID",
                        "name": "team_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "user_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Is Manager Status (1 = true, 0 = false)",
                        "name": "is_manager",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status updated successfully"
                    }
                }
            }
        },
        "/teams/{uuid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a team and its members by the provided UUID. 🔒 Requires role: **any**",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Get team by UUID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Team retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/model.TeamReadAll"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a team by the provided UUID. 🔒 Requires role: **admin**",
                "tags": [
                    "Teams"
                ],
                "summary": "Delete team by UUID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Team deleted successfully"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of all registered users. 🔒 Requires role: **admin**",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "List of users retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.UserRead"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates user information such as username, email, name, and roles. Only the **UUID** is mandatory. The **username** will be auto generated with first letter of the first name + last name on every update. 🔒 Requires role: **admin**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user details",
                "parameters": [
                    {
                        "description": "User update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserUpdateEntry"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User updated successfully",
                        "schema": {
                            "$ref": "#/definitions/response.UserUpdatedResponse"
                        }
                    }
                }
            }
        },
        "/users/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a user by their UUID. 🔒 Requires role: **admin**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "description": "User UUID payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserUUIDPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/response.UserDeletedResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new user with the provided information. 🔒 Requires role: **admin**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User creation payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User registered successfully",
                        "schema": {
                            "$ref": "#/definitions/response.UserCreatedResponse"
                        }
                    }
                }
            }
        },
        "/users/update-status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a user's status (active, disabled, or pending). 🔒 Requires role: **admin**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user status",
                "parameters": [
                    {
                        "description": "User status update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserStatusUpdatePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User status updated successfully",
                        "schema": {
                            "$ref": "#/definitions/response.UserStatusUpdatedResponse"
                        }
                    }
                }
            }
        },
        "/users/weekly-rates": {
            "get": {
                "description": "Retrieve a list of all weekly rates",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WeeklyRates"
                ],
                "summary": "Get all weekly rates",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.WeeklyRate"
                            }
                        }
                    }
                }
            }
        },
        "/users/weekly-rates/create": {
            "post": {
                "description": "Create a new weekly rate with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WeeklyRates"
                ],
                "summary": "Create a new weekly rate",
                "parameters": [
                    {
                        "description": "Weekly Rate Data",
                        "name": "weeklyRate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateWeeklyRate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Weekly rate created successfully"
                    }
                }
            }
        },
        "/users/weekly-rates/{uuid}/update": {
            "put": {
                "description": "Update the details of an existing weekly rate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WeeklyRates"
                ],
                "summary": "Update an existing weekly rate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Weekly Rate UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Weekly Rate Data",
                        "name": "weeklyRate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateWeeklyRate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Weekly rate updated successfully"
                    }
                }
            }
        },
        "/users/{uuid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the details of a user identified by their UUID or not. If the UUID is not specificed it will return the current logged in users details. To query an other user data, must be manager or admin 🔒 Requires role: **all**",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user by UUID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/model.UserReadAll"
                        }
                    }
                }
            }
        },
        "/work-session/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns paginated history of work sessions between a start and end date 🔒 Requires role: **admin or manager** to get history from any users. If the user is employee, only their own history can be accessed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WorkSession"
                ],
                "summary": "Get user work session history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID of the user (optional, defaults to authenticated user)",
                        "name": "user_uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date in ISO 8601 format (from 2 years ago up to now)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date in ISO 8601 format (can't be in the future)",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return (default 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of work session history entries",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.WorkSessionReadHistory"
                            }
                        }
                    }
                }
            }
        },
        "/work-session/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns whether the authenticated user is currently clocked in 🔒 Requires role: **any**",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WorkSession"
                ],
                "summary": "Get current work session status",
                "responses": {
                    "200": {
                        "description": "Current work session status",
                        "schema": {
                            "$ref": "#/definitions/model.WorkSessionStatus"
                        }
                    }
                }
            }
        },
        "/work-session/update-breaking": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts or ends a break for the current work session depending on the value of ` + "`" + `is_breaking` + "`" + `. 🔒 Requires role: **any**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WorkSession"
                ],
                "summary": "Update break status",
                "parameters": [
                    {
                        "description": "Break update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.BreakUpdate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Break updated successfully",
                        "schema": {
                            "$ref": "#/definitions/model.BreakUpdateResponse"
                        }
                    }
                }
            }
        },
        "/work-session/update-clocking": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts or stops a work session for the authenticated user 🔒 Requires role: **any**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WorkSession"
                ],
                "summary": "Update work session clocking status",
                "parameters": [
                    {
                        "description": "Clocking payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.WorkSessionUpdate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Work session updated successfully",
                        "schema": {
                            "$ref": "#/definitions/model.WorkSessionUpdateResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.BreakUpdate": {
            "type": "object",
            "properties": {
                "is_breaking": {
                    "type": "boolean"
                },
                "work_session_uuid": {
                    "type": "string"
                }
            }
        },
        "model.BreakUpdateResponse": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "model.CreateWeeklyRate": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "rate_name": {
                    "type": "string"
                }
            }
        },
        "model.NewTeamMember": {
            "type": "object",
            "required": [
                "user_uuid"
            ],
            "properties": {
                "is_manager": {
                    "type": "boolean"
                },
                "user_uuid": {
                    "type": "string"
                }
            }
        },
        "model.TeamAddUsers": {
            "type": "object",
            "required": [
                "member_uuids",
                "team_uuid"
            ],
            "properties": {
                "member_uuids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NewTeamMember"
                    }
                },
                "team_uuid": {
                    "type": "string"
                }
            }
        },
        "model.TeamCreate": {
            "type": "object",
            "required": [
                "member_uuids",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "member_uuids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NewTeamMember"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.TeamMember": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "is_manager": {
                    "type": "boolean"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "user_uuid": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "weekly_rate": {
                    "type": "integer"
                },
                "weekly_rate_name": {
                    "type": "string"
                },
                "work_session_status": {
                    "type": "string"
                }
            }
        },
        "model.TeamReadAll": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "team_members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TeamMember"
                    }
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.TeamUpdate": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.UpdateWeeklyRate": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "rate_name": {
                    "type": "string"
                }
            }
        },
        "model.UserCreate": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "description": "Ignored by GORM, used only for input",
                    "type": "string"
                },
                "password_hash": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.UserMeJWT": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "user_uuid": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UserRead": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "weekly_rate": {
                    "type": "integer"
                },
                "weekly_rate_name": {
                    "type": "string"
                },
                "work_session_status": {
                    "type": "string"
                }
            }
        },
        "model.UserReadAll": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "teams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.UserTeamMemberInfo"
                    }
                },
                "username": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "weekly_rate": {
                    "type": "integer"
                },
                "weekly_rate_name": {
                    "type": "string"
                },
                "work_session_status": {
                    "type": "string"
                }
            }
        },
        "model.UserStatusUpdatePayload": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "user_uuid": {
                    "type": "string",
                    "example": "e1234abc-5678-90de-f123-4567890abcde"
                }
            }
        },
        "model.UserTeamMemberInfo": {
            "type": "object",
            "properties": {
                "is_manager": {
                    "type": "boolean",
                    "example": true
                },
                "team_description": {
                    "type": "string",
                    "example": "Équipe principale backend"
                },
                "team_name": {
                    "type": "string",
                    "example": "Développement"
                },
                "team_uuid": {
                    "type": "string",
                    "example": "4bc3df44-491c-4073-9e89-682bb0acfca0"
                }
            }
        },
        "model.UserUUIDPayload": {
            "type": "object",
            "properties": {
                "user_uuid": {
                    "type": "string",
                    "example": "e1234abc-5678-90de-f123-4567890abcde"
                }
            }
        },
        "model.UserUpdateEntry": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.WeeklyRate": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "rate_name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.WorkSessionReadHistory": {
            "type": "object",
            "properties": {
                "breaks_duration_minutes": {
                    "type": "integer"
                },
                "clock_in": {
                    "type": "string"
                },
                "clock_out": {
                    "type": "string"
                },
                "duration_minutes": {
                    "type": "integer"
                },
                "status": {
                    "description": "status is either \"active\", \"paused\" or \"completed\"",
                    "type": "string"
                },
                "user_uuid": {
                    "description": "User fields",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "work_session_uuid": {
                    "type": "string"
                }
            }
        },
        "model.WorkSessionStatus": {
            "type": "object",
            "properties": {
                "clock_in_time": {
                    "type": "string"
                },
                "is_clocked": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "work_session_uuid": {
                    "type": "string"
                }
            }
        },
        "model.WorkSessionUpdate": {
            "type": "object",
            "properties": {
                "is_clocked": {
                    "type": "boolean"
                },
                "user_uuid": {
                    "type": "string"
                }
            }
        },
        "model.WorkSessionUpdateResponse": {
            "type": "object",
            "properties": {
                "clock_in_time": {
                    "type": "string"
                },
                "clock_out_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "logged in successfully"
                }
            }
        },
        "response.UserCreatedResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "user registered successfully"
                }
            }
        },
        "response.UserDeletedResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "user deleted successfully"
                }
            }
        },
        "response.UserStatusUpdatedResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "user status updated successfully"
                }
            }
        },
        "response.UserUpdatedResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "user updated successfully"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
