// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates a user via email or username and returns a JWT cookie on success.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login a user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "logged in successfully",
                        "schema": {
                            "$ref": "#/definitions/response.MessageResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Clears the JWT cookie and invalidates the user's session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout the current user",
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "schema": {
                            "$ref": "#/definitions/response.MessageResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves information about the currently logged-in user based on the JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current user info",
                "responses": {
                    "200": {
                        "description": "Current user information",
                        "schema": {
                            "$ref": "#/definitions/model.UserMeJWT"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of all registered users. 🔒 Requires role: **admin**",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "List of users retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.UserRead"
                            }
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new user with the provided information. 🔒 Requires role: **admin**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User creation payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User registered successfully",
                        "schema": {
                            "$ref": "#/definitions/response.UserCreatedResponse"
                        }
                    }
                }
            }
        },
        "/users/update-status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a user's status (active, disabled, or pending). 🔒 Requires role: **admin**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user status",
                "parameters": [
                    {
                        "description": "User status update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserStatusUpdatePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User status updated successfully",
                        "schema": {
                            "$ref": "#/definitions/response.UserStatusUpdatedResponse"
                        }
                    }
                }
            }
        },
        "/users/{uuid}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a user by their UUID. 🔒 Requires role: **admin**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/response.UserDeletedResponse"
                        }
                    }
                }
            }
        },
        "/work-session/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns paginated history of work sessions between a start and end date 🔒 Requires role: **admin or manager** to get history from any users. If the user is employee, only their own history can be accessed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WorkSession"
                ],
                "summary": "Get user work session history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID of the user (optional, defaults to authenticated user)",
                        "name": "user_uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date in ISO 8601 format (from 2 years ago up to now)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date in ISO 8601 format (can't be in the future)",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return (default 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of work session history entries",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.WorkSessionReadHistory"
                            }
                        }
                    }
                }
            }
        },
        "/work-session/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns whether the authenticated user is currently clocked in 🔒 Requires role: **any**",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WorkSession"
                ],
                "summary": "Get current work session status",
                "responses": {
                    "200": {
                        "description": "Current work session status",
                        "schema": {
                            "$ref": "#/definitions/model.WorkSessionStatus"
                        }
                    }
                }
            }
        },
        "/work-session/update-breaking": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts or ends a break for the current work session depending on the value of ` + "`" + `is_breaking` + "`" + `. 🔒 Requires role: **any**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WorkSession"
                ],
                "summary": "Update break status",
                "parameters": [
                    {
                        "description": "Break update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.BreakUpdate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Break updated successfully",
                        "schema": {
                            "$ref": "#/definitions/model.BreakUpdateResponse"
                        }
                    }
                }
            }
        },
        "/work-session/update-clocking": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts or stops a work session for the authenticated user 🔒 Requires role: **any**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WorkSession"
                ],
                "summary": "Update work session clocking status",
                "parameters": [
                    {
                        "description": "Clocking payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.WorkSessionUpdate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Work session updated successfully",
                        "schema": {
                            "$ref": "#/definitions/model.WorkSessionUpdateResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.BreakUpdate": {
            "type": "object",
            "properties": {
                "is_breaking": {
                    "type": "boolean"
                },
                "work_session_uuid": {
                    "type": "string"
                }
            }
        },
        "model.BreakUpdateResponse": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "model.UserCreate": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "description": "Ignored by GORM, used only for input",
                    "type": "string"
                },
                "password_hash": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.UserMeJWT": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "user_uuid": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UserRead": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.UserStatusUpdatePayload": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "user_uuid": {
                    "type": "string",
                    "example": "e1234abc-5678-90de-f123-4567890abcde"
                }
            }
        },
        "model.WorkSessionReadHistory": {
            "type": "object",
            "properties": {
                "breaks_duration_minutes": {
                    "type": "integer"
                },
                "clock_in": {
                    "type": "string"
                },
                "clock_out": {
                    "type": "string"
                },
                "duration_minutes": {
                    "type": "integer"
                },
                "status": {
                    "description": "status is either \"active\", \"paused\" or \"completed\"",
                    "type": "string"
                },
                "user_uuid": {
                    "description": "User fields",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "work_session_uuid": {
                    "type": "string"
                }
            }
        },
        "model.WorkSessionStatus": {
            "type": "object",
            "properties": {
                "clock_in_time": {
                    "type": "string"
                },
                "is_clocked": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "work_session_uuid": {
                    "type": "string"
                }
            }
        },
        "model.WorkSessionUpdate": {
            "type": "object",
            "properties": {
                "is_clocked": {
                    "type": "boolean"
                },
                "user_uuid": {
                    "type": "string"
                }
            }
        },
        "model.WorkSessionUpdateResponse": {
            "type": "object",
            "properties": {
                "clock_in_time": {
                    "type": "string"
                },
                "clock_out_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "logged in successfully"
                }
            }
        },
        "response.UserCreatedResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "user registered successfully"
                }
            }
        },
        "response.UserDeletedResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "user deleted successfully"
                }
            }
        },
        "response.UserStatusUpdatedResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "user status updated successfully"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
